### ISSUE TITLE
Can I call runNext() multiple times?

### ISSUE THREAD

**Issue by sferrini** [pascalbros/Me#3]
I was wandering if the library was thought to being able to run the next block multiple times.
And if yes, when one should call the `end()` function (if the last block is called multiple times)?

**Comment by pascalbros** [comment]
Basically you can do what you want with ’runNext()’
My idea is to add a "counter" in additional data and check it, when it reaches a certain value, then call end() function.

**Comment by sferrini** [comment]
The problem with this is that if I change (let's say) a boolean in the `me.parameters` the first iteration, the second one will override that boolean:

```swift
Me.start { (me) in
    MyAPI.posts { posts in
        for (index, post) in posts.enumerated() {
            if let post = post {
                me.parameters["post"] = post
                me.parameters["stop"] = index < (posts.count - 1) ? false : true
                me.runNext()
            }
        }
    }
}.next { (caller, me) in
    MyAPI.likes(post: caller.parameters["post"]) {
        if caller?.parameters["stop"] as! Bool == true {
            me.end()
        }
    }
}.run()
```

And `caller?.parameters["stop"]` will be always `true` cause the next block is called asynchronously and the `for` has already iterated again.

Did I get your advice in a wrong way? Thanks

**Comment by pascalbros** [comment]
What if:

```
next { (caller, me) in
    let shouldStop = caller!.parameters["stop"]

    MyAPI.likes(post: caller.parameters["post"]) {
        if shouldStop as! Bool == true {
            me.end()
        }
    }
}.run()
```

**Comment by sferrini** [comment]
Yeah that should work, thanks! 👍
